services:
   main:
     container_name: main
     build:
       context: .
     env_file:
       - .env
     ports:
       - 3000:3000
     depends_on:
       - postgres
     restart: always
     networks:
       - network
   postgres:
     container_name: postgres
     image: postgres:12
     env_file:
       - .env
     volumes:
       - ./postgres/data:/var/lib/postgresql/data
     ports:
       - 5434:5432
     restart: always
     networks:
       - network
networks:
   network:
     driver: bridge
     name: network
     external: false